# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gradebook_tool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 82)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 6, 0, 1, 4)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tab)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 7, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 1, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.treeWidget = QtWidgets.QTreeWidget(self.tab)
        self.treeWidget.setAutoFillBackground(False)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setWordWrap(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        item_0.setFont(0, font)
        item_0.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4.setCheckState(0, QtCore.Qt.Checked)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_4.setBackground(0, brush)
        item_4.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_4.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4.setCheckState(0, QtCore.Qt.Checked)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4.setCheckState(0, QtCore.Qt.Checked)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4.setCheckState(0, QtCore.Qt.Checked)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4.setCheckState(0, QtCore.Qt.Checked)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3.setCheckState(0, QtCore.Qt.Checked)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3.setCheckState(0, QtCore.Qt.PartiallyChecked)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3.setCheckState(0, QtCore.Qt.Checked)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(0, QtCore.Qt.Unchecked)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_2.addWidget(self.treeWidget, 2, 0, 3, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 3, QtCore.Qt.AlignLeft)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(61, 100))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.gridLayout_2.addWidget(self.groupBox_3, 3, 2, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.Column = QtWidgets.QWidget()
        self.Column.setObjectName("Column")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Column)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.Column)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.gridLayout_4.addWidget(self.listWidget_3, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.groupBox = QtWidgets.QGroupBox(self.Column)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.gridLayout_4.addWidget(self.groupBox, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Column)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.Column, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "230 Files Found"))
        self.pushButton.setText(_translate("MainWindow", "Browse..."))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Gradebook Data"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "D2L Data"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "A&S"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "AAST"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(0, _translate("MainWindow", "Archived"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(0).setText(0, _translate("MainWindow", "Fall 17"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(1).setText(0, _translate("MainWindow", "Fall 18"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(2).setText(0, _translate("MainWindow", "Spring 18"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(3).setText(0, _translate("MainWindow", "Summer 17"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).child(4).setText(0, _translate("MainWindow", "Summer 18"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(0, _translate("MainWindow", "Spring 19"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "AllGradesWithWithdrawnStudents_20190509_182623_LEAD111-50699-201920.csv"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(1).setText(0, _translate("MainWindow", "AllGradesWithWithdrawnStudents_20190509_182623_LEAD123-28394-201920.csv"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).child(2).setText(0, _translate("MainWindow", "AllGradesWithWithdrawnStudents_20190509_182623_MILS231-28239-201920.csv"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(2).setText(0, _translate("MainWindow", "Summer 19"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "BCA"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "Archived"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(1).setText(0, _translate("MainWindow", "Spring 19"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(2).setText(0, _translate("MainWindow", "Summer 19"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "CTL"))
        self.treeWidget.topLevelItem(0).child(0).child(2).child(0).setText(0, _translate("MainWindow", "Archived"))
        self.treeWidget.topLevelItem(0).child(0).child(2).child(1).setText(0, _translate("MainWindow", "Spring 2019"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "HHS"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "TC"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setText(_translate("MainWindow", "C:\\Users\\razzi\\Desktop\\D2L Data"))
        self.label_4.setText(_translate("MainWindow", "138 Selected"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Statistics"))
        self.label.setText(_translate("MainWindow", "Instructors (5):"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Bell, Aniseh"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "James, Clark"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Jessica, Joel"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Elias, Terry"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Brown, Cherie"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Term Range (6):"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "201810 - Fall 2017"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "201820 - Spring 2018"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "201830 - Summer 2018"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", "201910 - Fall 2019"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("MainWindow", "201920 - Spring 2019"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("MainWindow", "201930 - Summer 2019"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Gradebook Data"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Select gradebook information"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "FirstName"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "LastName"))
        item = self.listWidget_3.item(3)
        item.setText(_translate("MainWindow", "RoleId"))
        item = self.listWidget_3.item(4)
        item.setText(_translate("MainWindow", "RoleName"))
        item = self.listWidget_3.item(5)
        item.setText(_translate("MainWindow", "CourseOfferingId"))
        item = self.listWidget_3.item(6)
        item.setText(_translate("MainWindow", "CourseOfferingCode"))
        item = self.listWidget_3.item(7)
        item.setText(_translate("MainWindow", "CourseOfferingName"))
        item = self.listWidget_3.item(8)
        item.setText(_translate("MainWindow", "CourseSectionCode"))
        item = self.listWidget_3.item(9)
        item.setText(_translate("MainWindow", "GradeItemCategoryId"))
        item = self.listWidget_3.item(10)
        item.setText(_translate("MainWindow", "GradeItemCategoryName"))
        item = self.listWidget_3.item(11)
        item.setText(_translate("MainWindow", "GradeItemId"))
        item = self.listWidget_3.item(12)
        item.setText(_translate("MainWindow", "GradeItemName"))
        item = self.listWidget_3.item(13)
        item.setText(_translate("MainWindow", "GradeItemWeight"))
        item = self.listWidget_3.item(14)
        item.setText(_translate("MainWindow", "PointsNumerator"))
        item = self.listWidget_3.item(15)
        item.setText(_translate("MainWindow", "PointsDenominator"))
        item = self.listWidget_3.item(16)
        item.setText(_translate("MainWindow", "GradeValue"))
        item = self.listWidget_3.item(17)
        item.setText(_translate("MainWindow", "GradeLastModified"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Processing Method"))
        self.label_5.setText(_translate("MainWindow", "Validation"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Numeric"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Mixed Field"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Plain Text"))
        self.comboBox.setItemText(3, _translate("MainWindow", "CRN"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Grade Item Name"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Grade Value"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Date"))
        self.label_6.setText(_translate("MainWindow", "Cleaning"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Numeric"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Mixed Field"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Plain Text"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Fuzzy Matching"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Grade Normalization"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Date"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Column), _translate("MainWindow", "Column Configuration"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Column), _translate("MainWindow", "Configure column settings"))

